#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define AWS_IOT_ENDPOINT "YOUR_ENDPOINT-ats.iot.us-east-2.amazonaws.com"
#define AWS_IOT_CLIENT_ID "station_001"

static const char AWS_ROOT_CA[] PROGMEM = R"ROOT_CA(
-----BEGIN CERTIFICATE-----
PASTE_AMAZON_ROOT_CA_1_HERE
-----END CERTIFICATE-----
)ROOT_CA";

static const char AWS_DEVICE_CERT[] PROGMEM = R"DEVICE_CERT(
-----BEGIN CERTIFICATE-----
PASTE_DEVICE_CERTIFICATE_HERE
-----END CERTIFICATE-----
)DEVICE_CERT";

static const char AWS_PRIVATE_KEY[] PROGMEM = R"PRIVATE_KEY(
-----BEGIN RSA PRIVATE KEY-----
PASTE_PRIVATE_KEY_HERE
-----END RSA PRIVATE KEY-----
)PRIVATE_KEY";